### ISSUE TITLE
Open SidebarCollapsibleCards swap open and closed states when dragged

### ISSUE THREAD

**Issue by lgariepy** [helpscout/blue#71]
I noticed an issue where SidebarCollapsibleCards swap their open and closed states when dragged:

<img src="https://d1ax1i5f2y3x71.cloudfront.net/items/40190W3S2B0u040I3431/Screen%20Recording%202017-10-12%20at%2011.02%20AM.gif?X-CloudApp-Visitor-Id=2723609&v=7ba34c60" />

It seems like the "open" state is remembered on the component in a particular position in the array and not the component itself. 

Thanks for your help!!

**Comment by ItsJonQ** [comment]
Thanks!! On it :)

**Comment by ItsJonQ** [comment]
Investigated… So! The Sortable component (using an external library, `react-sortable-hoc`) is doing unpredictable things with child component state.

I have no idea what that is yet… still trying to figure it out.

It works perfectly fine if child components are stateless though.

This is important because the SidebarCollapsibleCards maintain their own `isOpen` state.
